### ISSUE TITLE
Introdução

### ISSUE THREAD

**Issue by gregorystevao19** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t1-gastrocode-pmv#1]

**Comment by VivianePertence** [comment]
**Introdução**

Os jovens adultos enfrentam uma carga diária de atribuições onde é necessário um verdadeiro malabarismo para conciliar trabalho, estudo, compromissos familiares e sociais, entre outras diversas responsabilidades. Sendo assim, percebe-se que, diante do pouco tempo disponível, torna-se cada vez mais difícil dedicar tempo para organização de uma rotina de alimentação saudável.

A nutricionista Raquel Costa Ferreira destaca em seu artigo[1] que a falta de planejamento impacta diretamente na rotina de se ter uma alimentação saudável. Elaborar uma lista de compras que contenha opções de alimentos saudáveis, antes de ir ao supermercado ou feira, está entre os principais fatores que auxiliam na organização desta rotina.

Considerando os pontos citados, nossa proposta de projeto é a criação de uma Aplicação Web, o Gastro Code, direcionada especificamente para atender as demandas dos jovens adultos que buscam uma alimentação prática e saudável e que se encaixe em suas rotinas diárias. 

**[1]** - _Ferreira, Raquel Costa. *Como conciliar a falta de tempo e a necessidade de comer melhor?*. Publicado em: 23 de set. 2018.  Disponível em: https://saude.mpu.mp.br/noticias/como-conciliar-a-falta-de-tempo-e-a-necessidade-de-comer-melhor. Acesso em: 28 de ago. 2023._
