### ISSUE TITLE
Objetivos

### ISSUE THREAD

**Issue by gregorystevao19** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t1-gastrocode-pmv#3]

**Comment by AndressaSodre** [comment]
# Objetivos

## Objetivo Geral

O objetivo geral é proporcionar ao usuário o acesso a uma variedade de receitas saudáveis e de preparo descomplicado promovendo uma alimentação equilibrada sem deixar de valorizar o sabor dos alimentos.

## Objetivos Específicos

* Oferecer um catálogo diversificado de receitas práticas, fáceis e saborosas;
* Facilitar a busca de receitas com base no tempo de preparo e ingredientes, visando antender o tempo disponível e a preferência individual de cada usuário;
* Incorporar recursos interativos, como listas de compras geradas a partir da receita selecionada, auxiliando assim no planejamento e organização na rotina do usuário.
