### ISSUE TITLE
Justificativa

### ISSUE THREAD

**Issue by gregorystevao19** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t1-gastrocode-pmv#4]

**Comment by rfgunther** [comment]
**Justificativa para o Desenvolvimento de um Sistema Web de Receitas Saudáveis e Práticas para Jovens Adultos com Pouco Tempo Disponível**

Nos dias atuais, a busca por uma alimentação saudável e equilibrada é uma preocupação cada vez mais evidente na sociedade. No entanto, para jovens adultos que vivem uma rotina acelerada, conciliando estudos, trabalho e responsabilidades diárias, encontrar tempo e recursos para se alimentar de forma adequada pode ser um desafio significativo. Diante desse cenário, a proposta de desenvolver um sistema web que ofereça receitas de preparo fácil e rápido, além de disponibilizar uma lista de compras dos itens necessários para o preparo, surge como uma solução inovadora e necessária.

**Contextualização**:

Os jovens adultos que moram sozinhos enfrentam uma série de desafios relacionados à sua alimentação. A falta de tempo para planejar, comprar ingredientes e cozinhar refeições saudáveis muitas vezes resulta em escolhas menos nutritivas, como fast food e alimentos processados. Além disso, a comodidade das entregas de alimentos, embora sejam convenientes, muitas vezes não atende às necessidades nutricionais desses indivíduos.

**Importância e Relevância**:

O desenvolvimento de um sistema web que reúna receitas saudáveis e práticas direcionadas especificamente para jovens adultos solteiros se justifica por diversas razões:

**Promoção da Saúde**: A oferta de receitas balanceadas nutricionalmente contribui para a promoção da saúde e bem-estar dos jovens, reduzindo os riscos de problemas de saúde associados a uma alimentação inadequada.

**Economia de Tempo**: A disponibilização de receitas de preparo rápido e fácil otimiza o tempo dos usuários, permitindo que eles adotem uma alimentação saudável mesmo com uma agenda corrida.

**Facilitação do Planejamento**: A inclusão de listas de compras agiliza o processo de compra de ingredientes, evitando compras desnecessárias e reduzindo o desperdício de alimentos.

**Variedade de Opções**: A diversidade de receitas oferecidas pelo sistema evita a monotonia alimentar, incentivando os usuários a experimentar novos pratos e ingredientes.

**Acesso à Informação**: A plataforma proporciona acesso fácil a receitas e informações nutricionais, contribuindo para a educação alimentar dos usuários.

**Incentivo à Autonomia**: Ao capacitar os jovens adultos a preparar suas próprias refeições saudáveis, o sistema promove a autonomia e o desenvolvimento de habilidades culinárias.

A análise do consumo de tele-entrega de alimentos demonstra a crescente dependência desse serviço entre os jovens adultos com pouco tempo disponível. Embora a tele-entrega seja conveniente, muitas vezes as opções disponíveis não priorizam a saúde e a nutrição, levando a escolhas menos saudáveis, além de serem muito mais dispendiosas do que preparar em casa. O sistema proposto atua como uma alternativa que não apenas oferece comodidade, mas também incentiva escolhas alimentares mais conscientes.

Em resumo, a criação de um sistema web que forneça receitas saudáveis, listas de compras e opções de compra de ingredientes para jovens adultos é uma iniciativa que busca facilitar a adoção de uma alimentação balanceada mesmo em meio a uma rotina agitada. A abordagem abrange não apenas a praticidade, mas também a promoção da saúde e da educação alimentar, visando impactar positivamente a qualidade de vida desses indivíduos, além de que muito mais econômica.
